### ISSUE TITLE
Input Data 

### ISSUE THREAD

**Issue by stefanieberger** [theHamsta/farneback3d#4]
Hello Stephan!

Thank you for providing this implementation!

I am however wondering, how the numpy arrays (vol0 and vol1) should look like, to be able to use your code properly.
E.g. my images are 150*150 and I have a stack of 5 slices. 
How should the numpy array look like to work with your script? [5,150,150] or [150,150,5]?

Thanks :)
Stefanie

**Comment by theHamsta** [comment]
I guess you're trying to suggest that you're having 5 images and want to calculate the optical flow between them? This is not the purpose of this module (you can use OpenCV instead). This module is for comparing two volumes so any two numpy array with three indices and same size. So if you're dealing with volumes it will not matter if they are rotated.

**Comment by stefanieberger** [comment]
Hi, no sorry for the confusion! The above mentioned arrays are indeed 3D volumes. 
Alright, thanks!
